# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geosea
                                 A QGIS plugin
 Navegação marítima
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-03
        copyright            : (C) 2025 by Mirella F. Marques
        email                : mirellamarques@id.uff.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):  
    """Load geosea class from file geosea.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geosea import GeoseaPlugin
    return GeoseaPlugin(iface)

    from .geosea_dockwidget_base import geoseaDockWidget


    class GeoSeaDockWidgetWithIface(geoseaDockWidget):
        def __init__(self, parent=None):
            super().__init__(parent)
            self.set_iface(iface)
    
    return GeoSeaDockWidgetWithIface